### ISSUE TITLE
[어드민] 데이터베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by TwOneZero** [TwOneZero/project-board-admin#5]
어드민 프로젝트가 db 환경을 사용할 수 있게 세팅

### TODO
* [x] db 만들기
* [x] 계정 권한
* [x] IDE 접근 환경
* [x] repository 코드 작성
* [x] 관련 테스트 작성
